# fly.toml app configuration file generated for phonebook-backend-aged-dawn-3180 on 2024-12-30T21:20:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-aged-dawn-3180'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
